apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: vladisloves/src-report-service:v1
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_HOST
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PORT
        - name: RABBIT_MQ_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_USER
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: RABBIT_MQ_PASSWORD
        - name: RABBIT_MQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_QUEUE_NAME
        - name: RABBIT_MQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_EXCHANGE
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort:
