global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m

receivers:
  - name: 'default'
    email_configs:
      - to: 'ваша почта'
        from: 'alertmanager@yourdomain.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'ваша почта'
        auth_password: 'пароль для приложений'
    telegram_configs:
      - bot_token: 'ваш  токен'
        chat_id: вашчатид
        api_url: 'https://api.telegram.org'
        message: '{{ range .Alerts }}{{ .Annotations.description }} - {{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
